### ISSUE TITLE
GLOBAL AVARAGE and NA in Country column

### ISSUE THREAD

**Issue by sschmutz** [EmilHvitfeldt/index-challenge#1]
Hi Emil,
thank you for sharing/preparing these examples.

I noticed that there's a not so clean part at the end of `corruption-perception-index_2017_clean.csv`.
One could get rid of those two rows with something like `filter(!is.na(ISO3))` before ```select(Country, `CPI Score 2017`)```

PS: This is my first issue/pull-request, hope I did it as intended.

**Comment by EmilHvitfeldt** [comment]
Thank you very much for looking into this! You have done a great job with your first issue/pull-request! Keep it up :)
